### ISSUE TITLE
No module named 'test_cases'

### ISSUE THREAD

**Issue by ScorpJD** [KalChn/multi_vehicle_routing#1]
Hello, when I try to run this project, I got following error message
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    from test_cases import tasks_9 as predefined_tasks
ModuleNotFoundError: No module named 'test_cases'

Could you please let me know how to fix it? Thanks!

**Comment by KalChn** [comment]
hi there, thanks for reminding me of the test cases. i've uploaded some. you may try it again.
